//
//  School.swift
//  20210930-JoshuaChoi-NYCSchools
//
//  Created by Joshua Choi on 9/29/21.
//

import UIKit

struct School: Codable {
    
    var dbn,
        schoolName,
        boro,
        overview_paragraph,
        school_10th_seats,
        academicopportunities1,
        academicopportunities2,
        ell_programs,
        neighborhood,
        building_code,
        location,
        phone_number,
        fax_number,
        school_email,
        website,
        subway,
        bus,
        grades2018,
        finalgrades,
        total_students,
        extracurricular_activities,
        school_sports,
        attendance_rate,
        pct_stu_enough_variety,
        pct_stu_safe,
        school_accessibility_description,
        directions1,
        requirement1_1,
        requirement2_1,
        requirement3_1,
        requirement4_1,
        requirement5_1,
        offer_rate1,
        program1,
        code1,
        interest1,
        method1,
        seats9ge1,
        grade9gefilledflag1,
        grade9geapplicants1,
        seats9swd1,
        grade9swdfilledflag1,
        grade9swdapplicants1,
        seats101,
        admissionspriority11,
        admissionspriority21,
        admissionspriority31,
        grade9geapplicantsperseat1,
        grade9swdapplicantsperseat1,
        primary_address_line_1,
        city,
        zip,
        state_code,
        latitude,
        longitude,
        community_board,
        council_district,
        census_tract,
        bin,
        bbl,
        nta,
        borough: String?
}
